sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t srueda27/docker-react .

script:
  - docker run -e CI=true srueda27/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Frontend-Docker-React"
  env: "Frontend-Docker-React-env"
  bucket_name: "elasticbeanstalk-us-east-1-921016838065"
  bucket_path: "Frontend-Docker-React"
  on:
    branch: main
  access_key_id: ${AWS_ACCESS_KEY_DOCKER}
  secret_access_key: ${AWS_SECRET_KEY_DOCKER}