# To run: docker-compose up --build
# The --build flag is use to rebuild the images everytime and get all the updates from the code or Docker files
version: '3'
services: 
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4005:3000"
    volumes:
      - /app/node_modules
      - .:/app
  # tests:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /home/node/app/node_modules
  #     - ~/frontend:/home/node/app
  #   command: ["npm", "run", "test"]