version: '3'
services: 
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:3000"
    volumes:
      - /home/node/app/node_modules
      - ~/frontend:/home/node/app
  # tests:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /home/node/app/node_modules
  #     - ~/frontend:/home/node/app
  #   command: ["npm", "run", "test"]